version: "3.6"
services:
  postgres:
    image: postgres:14
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Chandu@1994
      POSTGRES_USER: postgres
      POSTGRES_DB: fractionTestDB
  rabbitmq:
    image: rabbitmq:3.9
    container_name: rabbitmq
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  paymentApp:
    container_name: fraction-payments
    image: fraction-payments:latest
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - postgres
      - rabbitmq
    restart: always
networks:
  default:
    name: fractionNetwork





